### ISSUE TITLE
Build hangs after export.

### ISSUE THREAD

**Issue by kiesenverseist** [GameDrivenDesign/docker-godot-export#1]
When running the build on travis, it seems to stop working after it exports all the scenes. The build doesn't fail for another 10 or so minutes, when the timer runs out. The export works fine locally on my windows 10 machine.

![image](https://user-images.githubusercontent.com/19500569/44907069-25583600-ad5a-11e8-9950-bc0529ac03e0.png)

I had noticed that the version used was 3.0.2, and I was running 3.0.6, so I in my own docker switched to that version in headless format (since that apparently has all the editor tools), where the issue persists. Another change was the signing key to glibc, its URL was changed.

I tried it again, this time using the server version, but it appears to not produce any file:
![image](https://user-images.githubusercontent.com/19500569/44907514-803e5d00-ad5b-11e8-8e44-d6191ccc6237.png)

This is the first time I've done any sort of CI, so I'm a little lost on what I'm doing wrong, any help would be much appreciated.

My own Dockerfile: https://github.com/kiesenverseist/docker-godot-export/blob/develop/Dockerfile
The travis.yml: https://github.com/kiesenverseist/equilibria/blob/master/.travis.yml

**Comment by kiesenverseist** [comment]
Thanks, although it didn't end up working. I'll try to recreate a minimum test project for a few different versions of Godot and then submit an issue to their page later.

**Comment by kiesenverseist** [comment]
As an update to all this, I managed to get this working, and have even managed to build for 3.1 alpha 2 over at my own fork. Thank you for your time earlier.

**Comment by tom95** [comment]
Hey @kiesenverseist great that you got it working! If I see correctly using a different glibc did the trick for you or were more changes required? We would definitely welcome a PR to incorporate your fixes here as well :)
