### ISSUE TITLE
Error on build due to version > 3.0

### ISSUE THREAD

**Issue by brettsaunders21** [GameDrivenDesign/docker-godot-export#4]
Error when building, seems to be related to Godot version
[Logs.txt](https://github.com/GameDrivenDesign/docker-godot-export/files/3440784/Logs.txt)

**Comment by logo4poop** [comment]
I get the same error

**Comment by logo4poop** [comment]
I have been trying to move to godot 3.1
I have found out that the alpine-glibc repo is broken and they have a new link now

**Comment by tom95** [comment]
Hey, if either of you have time to create a pull request that fixes the issue, we'll merge it right away! Otherwise we probably won't have time to look into this before next week at the earliest

**Comment by logo4poop** [comment]
The issue is that you need the export_presets file. I will fork it however to hopefully get alpine working

**Comment by logo4poop** [comment]
https://github.com/GameDrivenDesign/docker-godot-export/pull/5 should work

**Comment by logo4poop** [comment]
Also make it more clear that you need the export_presets.cfg for it to work

**Comment by cmfcmf** [comment]
> Also make it more clear that you need the export_presets.cfg for it to work

I've added a note about this file in https://github.com/GameDrivenDesign/docker-godot-export/commit/666f66f9145ba4b97498218134455cce1f9d0a24.
