### ISSUE TITLE
Godot 3.2.2?

### ISSUE THREAD

**Issue by k4y4k** [GameDrivenDesign/docker-godot-export#9]
I can't see the tag on Docker Hub.

I'm not sure what's been added in `3.2.2` that's made it better than `3.2.1`, so I'll go ahead and use that, and I suppose I'll be back if I've got problems? 🤞.

**Comment by tom95** [comment]
Hi! 3.2.2 is still in beta at the moment. We currently only suppport the stable versions. If you need to have the beta version, please reopen the ticket and we'll see what we can do :)
